services:
  - type: web
    name: video-compressor
    env: node
    buildCommand: |
      apt-get update
      apt-get install -y ffmpeg
      npm install
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production